kestra:
  server:
    basic-auth:
      enabled: ${KESTRA_SERVER_BASIC_AUTH_ENABLED:-false}
    cors:
      enabled: ${KESTRA_SERVER_CORS_ENABLED:-true}
      allowed-origins:
        - ${KESTRA_SERVER_CORS_ALLOWED_ORIGINS:-*}
  
  repository:
    type: postgres
  
  storage:
    type: local
    local:
      base-path: /app/storage
  
  queue:
    type: ${KESTRA_QUEUE_TYPE:-redis}
  
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver: org.postgresql.Driver
    max-pool-size: 10
  
  url: ${KESTRA_CONFIGURATION:-http://localhost:8080}

